### ISSUE TITLE
My only issue is that this is too good

### ISSUE THREAD

**Issue by dylanjrae** [jaquavis/GymBot#7]
This is the best idea of 2022 and I can't wait to use it to get around the stupid booking system. I salute the gym bot team

**Comment by jaquavis** [comment]
Thanks for the support😤
- the gymbot team

**Comment by lukegarland** [comment]
@djohnjames  its even better now. My fork has mac support. Check it out at https://github.com/lukegarland/GymBot/tree/mac-and-linux-support

**Comment by dylanjrae** [comment]
Wow, what a community working on this project. Can't wait until gymbot gets to the point where it just books me for every time slot of every day so I can go to the gym whenever. Issue resolved.
